### ISSUE TITLE
How to Obatain a TF-IDF File for Other Datasets?

### ISSUE THREAD

**Issue by Loycine** [qingzwang/DiversityMetrics#2]
I wonder how to obtain the TF-IDF file for a dataset which is not MSCOCO? 
I would be appreciate if you can share me a code or a detailed process to generate the TF-IDF file for other datasets.

**Comment by qingzwang** [comment]
Please take a look at [cider_scorer.py](https://github.com/qingzwang/DiversityMetrics/blob/master/pycocoevalcap/cider/cider_scorer.py), where there is a function named `compute_doc_freq`, which is used to compute the frequency of grams. Also, you can refer to [this file](https://github.com/qingzwang/self-critical.pytorch/blob/master/scripts/prepro_ngrams.py) to see how to compute TF-IDF. In your case, I think you can just change a few lines of the script to get the TF-IDF file.

**Comment by Loycine** [comment]
Thank you very much.  It is really a great help to me.
